p2: p2.c filelist.c cmdlist.c memlist.c funciones_p0.c funciones_p1.c funciones_p2.c
	gcc -o p2.out -Wall p2.c filelist.c cmdlist.c memlist.c funciones_p0.c funciones_p1.c funciones_p2.c
	
clear:
	rm *.out
