p2: p3.c filelist.c cmdlist.c memlist.c proclist.c dirlist.c funciones_p0.c funciones_p1.c funciones_p2.c funciones_p3.c
	gcc -o p3 -Wall p3.c filelist.c cmdlist.c memlist.c proclist.c dirlist.c funciones_p0.c funciones_p1.c funciones_p2.c funciones_p3.c
	
clear:
	rm *.out
